version: "2"

services:
  postgres:
    image: postgres
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: postgres
      DATABASE_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - localhost
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf

networks:
  localhost:
